#!/usr/bin/env bash

bundle_collect() {
  local outdir="$1"
  local name="$2"
  shift 2

  {
    echo "# ${name}"
    echo "# Collected: $(date -Is)"
    echo "# Command: $*"
    echo

    if have "$1"; then
      "$@" 2>&1 || true
    else
      echo "Command not found: $1"
    fi
  } | redact_stream > "${outdir}/${name}"
}

bundle_shell() {
  local outdir="$1"
  local name="$2"
  shift 2

  {
    echo "# ${name}"
    echo "# Collected: $(date -Is)"
    echo "# Shell: $*"
    echo
    bash -c "$*" 2>&1 || true
  } | redact_stream > "${outdir}/${name}"
}

create_bundle() {
  local ts
  local host
  local outdir
  local tarname

  ts="$(date '+%Y%m%d-%H%M%S')"
  host="$(hostname 2>/dev/null || echo host)"
  outdir="wwan-diag-bundle-${host}-${ts}"
  tarname="${outdir}.tar.gz"

  mkdir -p "${outdir}" || {
    echo "Failed to create bundle directory: ${outdir}" >&2
    exit 3
  }

  print_banner > "${outdir}/summary.txt"
  {
    print_system
    print_services
    print_rfkill
    print_networkmanager
    print_modemmanager
    print_hardware
    print_final_summary
  } | redact_stream >> "${outdir}/summary.txt"

  bundle_collect "${outdir}" "uname-a.txt" uname -a
  bundle_collect "${outdir}" "os-release.txt" cat /etc/os-release
  bundle_collect "${outdir}" "systemctl-networkmanager.txt" systemctl status NetworkManager.service --no-pager
  bundle_collect "${outdir}" "systemctl-modemmanager.txt" systemctl status ModemManager.service --no-pager
  bundle_collect "${outdir}" "nmcli-version.txt" nmcli --version
  bundle_collect "${outdir}" "nmcli-device-status.txt" nmcli device status
  bundle_collect "${outdir}" "nmcli-radio.txt" nmcli radio all
  bundle_collect "${outdir}" "nmcli-connections.txt" nmcli -f NAME,UUID,TYPE,DEVICE,AUTOCONNECT connection show
  bundle_collect "${outdir}" "mmcli-version.txt" mmcli --version
  bundle_collect "${outdir}" "mmcli-list.txt" mmcli -L
  bundle_collect "${outdir}" "rfkill.txt" rfkill list
  bundle_collect "${outdir}" "lsusb.txt" lsusb
  bundle_collect "${outdir}" "lsusb-tree.txt" lsusb -t
  bundle_collect "${outdir}" "lspci-nn.txt" lspci -nn
  bundle_shell "${outdir}" "ip-addr.txt" "ip addr show"
  bundle_shell "${outdir}" "ip-route.txt" "ip route show table all"
  bundle_shell "${outdir}" "dns-status.txt" "resolvectl status || systemd-resolve --status || cat /etc/resolv.conf"

  if have mmcli; then
    local id
    for id in $(modem_ids); do
      bundle_collect "${outdir}" "mmcli-modem-${id}.txt" mmcli -m "${id}"
      bundle_collect "${outdir}" "mmcli-modem-${id}-keyvalue.txt" mmcli -m "${id}" --output-keyvalue
      bundle_shell "${outdir}" "mmcli-modem-${id}-bearers.txt" "mmcli -m '${id}' --list-bearers"
    done
  fi

  if have journalctl; then
    bundle_shell "${outdir}" "journal-modemmanager-current-boot.txt" "journalctl -b -u ModemManager --no-pager"
    bundle_shell "${outdir}" "journal-networkmanager-current-boot.txt" "journalctl -b -u NetworkManager --no-pager"
    bundle_shell "${outdir}" "journal-wwan-filter-current-boot.txt" "journalctl -b --no-pager | grep -Ei 'modem|wwan|mbim|qmi|cdc-wdm|fibocom|quectel|sierra|ericsson|qualcomm|gobi|huawei|zte|novatel|telit|usb|rfkill' || true"
  else
    echo "journalctl not installed" > "${outdir}/journalctl-unavailable.txt"
  fi

  cat > "${outdir}/README.txt" <<EOF
This bundle was generated by wwan-diag-kit ${WWAN_DIAG_VERSION}.

The tool is intended to be read-only. It does not restart services, reset modems,
change NetworkManager profiles, unlock radios, or alter system configuration.

Basic redaction is applied for common modem identifiers, but review before
sharing publicly.
EOF

  tar -czf "${tarname}" "${outdir}" || {
    echo "Failed to create tarball: ${tarname}" >&2
    exit 3
  }

  rm -rf "${outdir}"

  echo "Created ${tarname}"
}
